# config file for Verdaccio
# based on  work from https://github.com/verdaccio/verdaccio/blob/master/packages/config/src/conf/docker.yaml

# NOTE: This is intended for local/dev use only, there is no authentication, nor security hardening.

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  title: Objectiv Verdaccio

auth:
  htpasswd:
    file: /dev/null
    # disable user registration
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@objectiv/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all

  '**':
    # allow all users (including non-authenticated users) to read all packages
    # we don't allow for publishing packages other than in the @objectiv scope
    access: $all
    publish: null
    unpublish: null

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a
# keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue
# https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs: { type: stdout, format: pretty, level: http }
